--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name: WWW-Search-PubMed
version: 1.001
abstract: Search the NCBI PubMed abstract database.
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::More: 0.61
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
license: perl
no_index:
  directory:
    - inc
    - t
requires:
    LWP::UserAgent:                0
    WWW::Search:                   0
    XML::DOM:                      0
